// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ParticleEffects
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DespawnParticleEffect : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static DespawnParticleEffect GetRootAsDespawnParticleEffect(ByteBuffer _bb) { return GetRootAsDespawnParticleEffect(_bb, new DespawnParticleEffect()); }
  public static DespawnParticleEffect GetRootAsDespawnParticleEffect(ByteBuffer _bb, DespawnParticleEffect obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DespawnParticleEffect __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Handle { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<ParticleEffects.DespawnParticleEffect> CreateDespawnParticleEffect(FlatBufferBuilder builder,
      ulong handle = 0) {
    builder.StartTable(1);
    DespawnParticleEffect.AddHandle(builder, handle);
    return DespawnParticleEffect.EndDespawnParticleEffect(builder);
  }

  public static void StartDespawnParticleEffect(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddHandle(FlatBufferBuilder builder, ulong handle) { builder.AddUlong(0, handle, 0); }
  public static Offset<ParticleEffects.DespawnParticleEffect> EndDespawnParticleEffect(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ParticleEffects.DespawnParticleEffect>(o);
  }
}


static public class DespawnParticleEffectVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Handle*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
