// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ParticleEffects
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SpawnParticleEffect : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SpawnParticleEffect GetRootAsSpawnParticleEffect(ByteBuffer _bb) { return GetRootAsSpawnParticleEffect(_bb, new SpawnParticleEffect()); }
  public static SpawnParticleEffect GetRootAsSpawnParticleEffect(ByteBuffer _bb, SpawnParticleEffect obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SpawnParticleEffect __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Handle { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint DescriptorAssetId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<ParticleEffects.SpawnParticleEffect> CreateSpawnParticleEffect(FlatBufferBuilder builder,
      ulong handle = 0,
      uint descriptor_asset_id = 0) {
    builder.StartTable(2);
    SpawnParticleEffect.AddHandle(builder, handle);
    SpawnParticleEffect.AddDescriptorAssetId(builder, descriptor_asset_id);
    return SpawnParticleEffect.EndSpawnParticleEffect(builder);
  }

  public static void StartSpawnParticleEffect(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddHandle(FlatBufferBuilder builder, ulong handle) { builder.AddUlong(0, handle, 0); }
  public static void AddDescriptorAssetId(FlatBufferBuilder builder, uint descriptorAssetId) { builder.AddUint(1, descriptorAssetId, 0); }
  public static Offset<ParticleEffects.SpawnParticleEffect> EndSpawnParticleEffect(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ParticleEffects.SpawnParticleEffect>(o);
  }
}


static public class SpawnParticleEffectVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Handle*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*DescriptorAssetId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
