// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Input
{

public enum ElementState : byte
{
  Pressed = 0,
  Released = 1,
};


}
