// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Input
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GamepadButton : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public GamepadButton __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public uint Index { get { return __p.bb.GetUint(__p.bb_pos + 4); } }
  public float Value { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

  public static Offset<Input.GamepadButton> CreateGamepadButton(FlatBufferBuilder builder, uint Id, uint Index, float Value) {
    builder.Prep(4, 12);
    builder.PutFloat(Value);
    builder.PutUint(Index);
    builder.PutUint(Id);
    return new Offset<Input.GamepadButton>(builder.Offset);
  }
}


}
