// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Input
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GamepadConnected : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static GamepadConnected GetRootAsGamepadConnected(ByteBuffer _bb) { return GetRootAsGamepadConnected(_bb, new GamepadConnected()); }
  public static GamepadConnected GetRootAsGamepadConnected(ByteBuffer _bb, GamepadConnected obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GamepadConnected __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint ButtonCount { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint AxisCount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Name { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<Input.GamepadConnected> CreateGamepadConnected(FlatBufferBuilder builder,
      uint id = 0,
      uint button_count = 0,
      uint axis_count = 0,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(4);
    GamepadConnected.AddName(builder, nameOffset);
    GamepadConnected.AddAxisCount(builder, axis_count);
    GamepadConnected.AddButtonCount(builder, button_count);
    GamepadConnected.AddId(builder, id);
    return GamepadConnected.EndGamepadConnected(builder);
  }

  public static void StartGamepadConnected(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static void AddButtonCount(FlatBufferBuilder builder, uint buttonCount) { builder.AddUint(1, buttonCount, 0); }
  public static void AddAxisCount(FlatBufferBuilder builder, uint axisCount) { builder.AddUint(2, axisCount, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(3, nameOffset.Value, 0); }
  public static Offset<Input.GamepadConnected> EndGamepadConnected(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Input.GamepadConnected>(o);
  }
}


static public class GamepadConnectedVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*ButtonCount*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*AxisCount*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 10 /*Name*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
