// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Input
{

public enum MouseButton : byte
{
  Left = 0,
  Right = 1,
  Middle = 2,
};


}
