// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Input
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MouseButtonInput : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public MouseButtonInput __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Input.MouseButton Button { get { return (Input.MouseButton)__p.bb.Get(__p.bb_pos + 0); } }
  public Input.ElementState State { get { return (Input.ElementState)__p.bb.Get(__p.bb_pos + 1); } }

  public static Offset<Input.MouseButtonInput> CreateMouseButtonInput(FlatBufferBuilder builder, Input.MouseButton Button, Input.ElementState State) {
    builder.Prep(1, 2);
    builder.PutByte((byte)State);
    builder.PutByte((byte)Button);
    return new Offset<Input.MouseButtonInput>(builder.Offset);
  }
}


}
