// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Input
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct WindowResized : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public WindowResized __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Width { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public uint Height { get { return __p.bb.GetUint(__p.bb_pos + 4); } }

  public static Offset<Input.WindowResized> CreateWindowResized(FlatBufferBuilder builder, uint Width, uint Height) {
    builder.Prep(4, 8);
    builder.PutUint(Height);
    builder.PutUint(Width);
    return new Offset<Input.WindowResized>(builder.Offset);
  }
}


}
