// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Input
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct WindowUnfocused : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public WindowUnfocused __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte WindowId { get { return __p.bb.Get(__p.bb_pos + 0); } }

  public static Offset<Input.WindowUnfocused> CreateWindowUnfocused(FlatBufferBuilder builder, byte WindowId) {
    builder.Prep(1, 1);
    builder.PutByte(WindowId);
    return new Offset<Input.WindowUnfocused>(builder.Offset);
  }
}


}
