// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Graphics
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DrawLine : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public DrawLine __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Vec2 From { get { return (new Vec2()).__assign(__p.bb_pos + 0, __p.bb); } }
  public Vec2 To { get { return (new Vec2()).__assign(__p.bb_pos + 8, __p.bb); } }
  public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 16); } }
  public float Thickness { get { return __p.bb.GetFloat(__p.bb_pos + 20); } }
  public Graphics.Color Color { get { return (new Graphics.Color()).__assign(__p.bb_pos + 24, __p.bb); } }

  public static Offset<Graphics.DrawLine> CreateDrawLine(FlatBufferBuilder builder, float from_X, float from_Y, float to_X, float to_Y, float Z, float Thickness, float color_R, float color_G, float color_B, float color_A) {
    builder.Prep(4, 40);
    builder.Prep(4, 16);
    builder.PutFloat(color_A);
    builder.PutFloat(color_B);
    builder.PutFloat(color_G);
    builder.PutFloat(color_R);
    builder.PutFloat(Thickness);
    builder.PutFloat(Z);
    builder.Prep(4, 8);
    builder.PutFloat(to_Y);
    builder.PutFloat(to_X);
    builder.Prep(4, 8);
    builder.PutFloat(from_Y);
    builder.PutFloat(from_X);
    return new Offset<Graphics.DrawLine>(builder.Offset);
  }
}


}
