// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Graphics
{

public enum TextAlignment : byte
{
  Left = 0,
  Center = 1,
  Right = 2,
};


}
